# Licensed under https://github.com/wpilibsuite/frc-docs-translations/blob/main/license.txt
name: Update and Deploy Translations
on:
  workflow_dispatch:
jobs:
  update-translations:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Update submodules
        run: git submodule update --remote --recursive
      - name: Setup Python and cache dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Install Transifex CLIAdd commentMore actions
        run: |
          curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
          mv tx /usr/local/bin/tx
      - name: Update translations
        run: bash -l scripts/update.sh
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - name: Lock unused Transifex resources
        run: python scripts/lock-translations.py .tx/config
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - name: Commit translation updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Translations from Transifex"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@users.noreply.github.com"
      - name: Build documentation
        run: sphinx-build -D language=ru -b html . _build/html -j auto
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _build/html
          force_orphan: true
          keep_files: false
