# Licensed under https://github.com/wpilibsuite/frc-docs-translations/blob/main/license.txt
name: Update Translations
on:
  workflow_dispatch:
jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Update Submodule
        run: |
          git submodule update --recursive --remote
      - name: Install Transifex CLI
        run: |
          curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
          mv tx /usr/local/bin/tx
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Update wheel
        run: |
          pip install wheel==0.34.2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Update Translations
        run: |
          bash -l scripts/update.sh
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - name: Lock Unused Transifex Resources
        run: |
          python scripts/lock-translations.py .tx/config
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - name: Create Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Translations from Transifex"
          commit_user_name: GitHub
          commit_user_email: noreply@github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      - name: Install Graphviz
        run: |
          sudo apt update
          sudo apt install -y graphviz
      - name: Build HTML
        run: |
          sphinx-build -D language=ru -b html . _build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          force_orphan: true
